"""empty message

Revision ID: 09601e22b109
Revises: 1555433ae8a0
Create Date: 2022-12-15 00:38:34.491335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09601e22b109'
down_revision = '1555433ae8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('overlapped_schedule',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.PickleType(),
               existing_nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('timetable_array',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.PickleType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('timetable_array',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('overlapped_schedule',
               existing_type=sa.PickleType(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
