"""empty message

Revision ID: 1555433ae8a0
Revises: 63a6516b5270
Create Date: 2022-12-14 23:52:21.881911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1555433ae8a0'
down_revision = '63a6516b5270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('overlapped_schedule',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('timetable_array',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('timetable_array',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('overlapped_schedule',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
