"""empty message

Revision ID: 48897fdf25ce
Revises: 55b2c3ca75e2
Create Date: 2022-12-04 15:45:44.811482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48897fdf25ce'
down_revision = '55b2c3ca75e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('period', sa.String(length=150), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('random_string', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan')),
    sa.UniqueConstraint('random_string', name=op.f('uq_plan_random_string'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan')
    # ### end Alembic commands ###
