"""empty message

Revision ID: 63a6516b5270
Revises: 5fa9130f9fdd
Create Date: 2022-12-14 21:11:03.364586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a6516b5270'
down_revision = '5fa9130f9fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('first_day',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('first_day',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
