"""empty message

Revision ID: 7ab8a6c471db
Revises: 48897fdf25ce
Create Date: 2022-12-06 16:54:37.366228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab8a6c471db'
down_revision = '48897fdf25ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_member_plan_id_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_plan_member_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan_id', name=op.f('pk_plan_member'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_member')
    # ### end Alembic commands ###
