"""empty message

Revision ID: ad5f0ee8c4b8
Revises: 4584f1ee3cf3
Create Date: 2022-12-11 11:04:04.427391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5f0ee8c4b8'
down_revision = '4584f1ee3cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_day', sa.String(length=150), nullable=False))
        batch_op.drop_column('period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('first_day')

    # ### end Alembic commands ###
